version: "3"
# Command deploy: docker stack deploy --compose-file=docker-compose.yaml dns
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    #container_name: piholewunbound
    image: piholewunbound:v3.2
    hostname: piholewunbound            #hostname for container
    networks:
      - pihole_net
      #  ipv4_address: 172.16.0.210 #**Change, use pihole address
    environment:
      TZ: 'America/Maceio'     #**Change to your timezone
      WEBPASSWORD: 'mypassword'   #**Change this is pihole web password, only used on container creation.
      PIHOLE_DNS_: '127.0.0.1#5335' # 'pwu_pihole'
    #deploy:
    #  mode: global
    #  placement:
    #   constraints: [node.platform.os == linux]
    #deploy: 
    #  mode: replicated
    #  replicas: 1
    #  placement:
    #    constraints: [node.role == manager]
    ports:
      #- "443:443/tcp"
      - "53:53/tcp"
#      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "53:53/udp"
      - "85:80/tcp"
    #restart: "unless-stopped"
    volumes: 
      - 'pwu_data:/data' # Pi-Hole GitHub
      #- './etc-pihole:/etc/pihole' # Oficial PiHole
      #- './etc-dnsmasq.d:/etc/dnsmasq.d' # Oficial PiHole
      #- './unbound:/etc/unbound/unbound.conf.d/'
    #volumes:
    #  - 'pihole_data:/data'
    #volumes:
    #  - "pihole_data:/etc/pihole"
    #  - "pihole_data:/etc/dnsmasq.d"
#    cap_add:
#      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
volumes:
  pwu_data:
    external: true
networks:
  pihole_net:
    driver: overlay
    attachable: true
    #driver: macvlan
    #driver_opts:
    #  parent: enp0s18 # ORIGINAL: ens18 #**Change this to your interface
    #ipam:
      #config:
        #- subnet: 172.16.0.0/24     #**Your network subnet
          #gateway: 172.16.0.1/24       #**Your network gateway
          #ip_range: 172.16.0.210/32  #**IP for pihole container
